"""empty message

Revision ID: 2fea5e69959c
Revises: 6d904f63c88e
Create Date: 2019-07-27 15:37:02.075441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fea5e69959c'
down_revision = '6d904f63c88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plurks', sa.Column('author_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plurks', 'author_name')
    # ### end Alembic commands ###
